# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 178d7f13aa56d9cb0d604884ea3a747739bf4bed327b5c95ab67c81ac182d76abdc1b7678b99c79c354d3ab2782c86755b288efbb27ae11c45ed793e64659aac

test:
  secret_key_base: 9417c051336a8fcb82307b55446c44bd0eefa2de5a22ff871ad057f235884e54da1b9f32550148c3633f39c32b8832f94ed15f0bea600442faa4b737de7578c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
